In [342]:
import pandas as pd
import numpy as np

In [343]:
def myarray(nx, ny):
    NX = nx
    NY = ny
    N = NX*NY
    b = np.zeros(N)
    b[0] = 1

    A = np.zeros(shape=(N,N))
    for i in range (1, N+1):
        #print(i)
        temp_array = np.zeros(N)
        if (i % NX != 0): #block does have a right neighbor
            temp_array[i-1+1] = -1
        if(i % NX != 1): #block does have a left neighbor
            temp_array[i-1-1] = -1
        if (i <= NX*(NY-1)): #block does have a top neighbor
            temp_array[i-1+nx] = -1
        if (i > NX): #block does have a bottom neighbor
            temp_array[i-1-NX] = -1
        temp_array[i-1] = abs(sum((temp_array)))
        A[i-1] = temp_array
    A[0][0] = 3  
    print("\nA is:")
    print(A)

    #Find solution to the system of equations Ax=b
    x = np.linalg.solve(A, b)
    print("\nx is:")
    print(x)
    
    #Check that the solution is correct:
    #print(np.allclose(np.dot(A, x), b))

In [344]:
myarray(2,3)


A is:
[[ 3. -1. -1.  0.  0.  0.]
 [-1.  2.  0. -1.  0.  0.]
 [-1.  0.  3. -1. -1.  0.]
 [ 0. -1. -1.  3.  0. -1.]
 [ 0.  0. -1.  0.  2. -1.]
 [ 0.  0.  0. -1. -1.  2.]]

x is:
[ 1.  1.  1.  1.  1.  1.]


In [345]:
myarray(3,2)


A is:
[[ 3. -1.  0. -1.  0.  0.]
 [-1.  3. -1.  0. -1.  0.]
 [ 0. -1.  2.  0.  0. -1.]
 [-1.  0.  0.  2. -1.  0.]
 [ 0. -1.  0. -1.  3. -1.]
 [ 0.  0. -1.  0. -1.  2.]]

x is:
[ 1.  1.  1.  1.  1.  1.]


In [346]:
myarray(3,3)


A is:
[[ 3. -1.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  3. -1.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  2.  0.  0. -1.  0.  0.  0.]
 [-1.  0.  0.  3. -1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  4. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.  3.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.  0.  2. -1.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  3. -1.]
 [ 0.  0.  0.  0.  0. -1.  0. -1.  2.]]

x is:
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [347]:
myarray(4,4)


A is:
[[ 3. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  3. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  3. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  3. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0. -1.  4. -1.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. -1.  4. -1.  0.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0. -1.  3.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  3. -1.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0. -1.  4. -1.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  4. -1.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  3.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -1.  3. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0. -